//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_pply.
        /// </summary>
        public static string BUTTON_APPLY_EXCLUDEPATTERN {
            get {
                return ResourceManager.GetString("BUTTON_APPLY_EXCLUDEPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply.
        /// </summary>
        public static string BUTTON_APPLY_INCLUDEPATTERN {
            get {
                return ResourceManager.GetString("BUTTON_APPLY_INCLUDEPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string CMD_ABOUT {
            get {
                return ResourceManager.GetString("CMD_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add des_tination directory....
        /// </summary>
        public static string CMD_ADD_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("CMD_ADD_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source files from di_rectory....
        /// </summary>
        public static string CMD_ADD_SOURCE_DIRECTORY {
            get {
                return ResourceManager.GetString("CMD_ADD_SOURCE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add source file....
        /// </summary>
        public static string CMD_ADD_SOURCE_FILE {
            get {
                return ResourceManager.GetString("CMD_ADD_SOURCE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Perform backup.
        /// </summary>
        public static string CMD_BACKUP {
            get {
                return ResourceManager.GetString("CMD_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string CMD_CLOSE {
            get {
                return ResourceManager.GetString("CMD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create new backup....
        /// </summary>
        public static string CMD_CREATE_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("CMD_CREATE_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete backup....
        /// </summary>
        public static string CMD_DELETE_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("CMD_DELETE_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string CMD_EXIT {
            get {
                return ResourceManager.GetString("CMD_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh.
        /// </summary>
        public static string CMD_REFRESH {
            get {
                return ResourceManager.GetString("CMD_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove _destination directory.
        /// </summary>
        public static string CMD_REMOVE_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("CMD_REMOVE_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_emove source file.
        /// </summary>
        public static string CMD_REMOVE_SOURCE_FILE {
            get {
                return ResourceManager.GetString("CMD_REMOVE_SOURCE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename backup....
        /// </summary>
        public static string CMD_RENAME_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("CMD_RENAME_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup finished.
        /// </summary>
        public static string COLUMN_BACKUP_FINISHED {
            get {
                return ResourceManager.GetString("COLUMN_BACKUP_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup started.
        /// </summary>
        public static string COLUMN_BACKUP_STARTED {
            get {
                return ResourceManager.GetString("COLUMN_BACKUP_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied files.
        /// </summary>
        public static string COLUMN_COPIED_FILES {
            get {
                return ResourceManager.GetString("COLUMN_COPIED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy errors.
        /// </summary>
        public static string COLUMN_COPY_ERRORS {
            get {
                return ResourceManager.GetString("COLUMN_COPY_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path.
        /// </summary>
        public static string COLUMN_DIRECTORY_PATH {
            get {
                return ResourceManager.GetString("COLUMN_DIRECTORY_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string COLUMN_FILEPATH {
            get {
                return ResourceManager.GetString("COLUMN_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string COLUMN_FILESIZE {
            get {
                return ResourceManager.GetString("COLUMN_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string COLUMN_LAST_MODIFIED {
            get {
                return ResourceManager.GetString("COLUMN_LAST_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic backup:.
        /// </summary>
        public static string LABEL_AUTOMATIC_BACKUP {
            get {
                return ResourceManager.GetString("LABEL_AUTOMATIC_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Backup:.
        /// </summary>
        public static string LABEL_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("LABEL_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des_tination directories:.
        /// </summary>
        public static string LABEL_DESTINATION_DIRECTORIES {
            get {
                return ResourceManager.GetString("LABEL_DESTINATION_DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xclude pattern:.
        /// </summary>
        public static string LABEL_EXCLUDE_PATTERN {
            get {
                return ResourceManager.GetString("LABEL_EXCLUDE_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished at:.
        /// </summary>
        public static string LABEL_FINISHED_AT {
            get {
                return ResourceManager.GetString("LABEL_FINISHED_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Include pattern:.
        /// </summary>
        public static string LABEL_INCLUDE_PATTERN {
            get {
                return ResourceManager.GetString("LABEL_INCLUDE_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup:.
        /// </summary>
        public static string LABEL_LAST_BACKUP {
            get {
                return ResourceManager.GetString("LABEL_LAST_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next backup at:.
        /// </summary>
        public static string LABEL_NEXT_BACKUP_AT {
            get {
                return ResourceManager.GetString("LABEL_NEXT_BACKUP_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Source files:.
        /// </summary>
        public static string LABEL_SOURCE_FILES {
            get {
                return ResourceManager.GetString("LABEL_SOURCE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at:.
        /// </summary>
        public static string LABEL_STARTED_AT {
            get {
                return ResourceManager.GetString("LABEL_STARTED_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MENUITEM_EDIT {
            get {
                return ResourceManager.GetString("MENUITEM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MENUITEM_FILE {
            get {
                return ResourceManager.GetString("MENUITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MENUITEM_HELP {
            get {
                return ResourceManager.GetString("MENUITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MENUITEM_VIEW {
            get {
                return ResourceManager.GetString("MENUITEM_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Daily.
        /// </summary>
        public static string OPTION_DAILY {
            get {
                return ResourceManager.GetString("OPTION_DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H_ourly.
        /// </summary>
        public static string OPTION_HOURLY {
            get {
                return ResourceManager.GetString("OPTION_HOURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Never.
        /// </summary>
        public static string OPTION_NEVER {
            get {
                return ResourceManager.GetString("OPTION_NEVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the backup &apos;{0}&apos;?.
        /// </summary>
        public static string QUESTION_DELETE_BACKUP_COLLECTION_0 {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_BACKUP_COLLECTION_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding destination directory....
        /// </summary>
        public static string TEXT_ADD_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("TEXT_ADD_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding source files from directory....
        /// </summary>
        public static string TEXT_ADD_SOURCE_FILES_FROM_DIRECTORY {
            get {
                return ResourceManager.GetString("TEXT_ADD_SOURCE_FILES_FROM_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing scheduled backup &apos;{0}&apos;....
        /// </summary>
        public static string TEXT_AUTOMATIC_BACKUP_0 {
            get {
                return ResourceManager.GetString("TEXT_AUTOMATIC_BACKUP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2020 Niels Stockfleth
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details..
        /// </summary>
        public static string TEXT_COPYRIGHT {
            get {
                return ResourceManager.GetString("TEXT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} destination file..
        /// </summary>
        public static string TEXT_DESTINATION_FILE_0 {
            get {
                return ResourceManager.GetString("TEXT_DESTINATION_FILE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} destination file of {1} selected..
        /// </summary>
        public static string TEXT_DESTINATION_FILE_SELECTED_0_1 {
            get {
                return ResourceManager.GetString("TEXT_DESTINATION_FILE_SELECTED_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} destination files..
        /// </summary>
        public static string TEXT_DESTINATION_FILES_0 {
            get {
                return ResourceManager.GetString("TEXT_DESTINATION_FILES_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} destination file of {1} selected..
        /// </summary>
        public static string TEXT_DESTINATION_FILES_SELECTED_0_1 {
            get {
                return ResourceManager.GetString("TEXT_DESTINATION_FILES_SELECTED_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. {0}.
        /// </summary>
        public static string TEXT_ERROR_OCCURRED_0 {
            get {
                return ResourceManager.GetString("TEXT_ERROR_OCCURRED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying patterns for source files....
        /// </summary>
        public static string TEXT_FILTERING_SOURCE_FILES {
            get {
                return ResourceManager.GetString("TEXT_FILTERING_SOURCE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading backup....
        /// </summary>
        public static string TEXT_LOAD_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("TEXT_LOAD_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing destination directory....
        /// </summary>
        public static string TEXT_REMOVE_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("TEXT_REMOVE_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing source files....
        /// </summary>
        public static string TEXT_REMOVE_SOURCE_FILES {
            get {
                return ResourceManager.GetString("TEXT_REMOVE_SOURCE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing backup....
        /// </summary>
        public static string TEXT_RUN_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("TEXT_RUN_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} source file..
        /// </summary>
        public static string TEXT_SOURCE_FILE_0 {
            get {
                return ResourceManager.GetString("TEXT_SOURCE_FILE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} source file of {1} selected..
        /// </summary>
        public static string TEXT_SOURCE_FILE_SELECTED_0_1 {
            get {
                return ResourceManager.GetString("TEXT_SOURCE_FILE_SELECTED_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} source files..
        /// </summary>
        public static string TEXT_SOURCE_FILES_0 {
            get {
                return ResourceManager.GetString("TEXT_SOURCE_FILES_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} source files of {1} selected..
        /// </summary>
        public static string TEXT_SOURCE_FILES_SELECTED_0_1 {
            get {
                return ResourceManager.GetString("TEXT_SOURCE_FILES_SELECTED_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add destination directory.
        /// </summary>
        public static string TITLE_ADD_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source files from directory.
        /// </summary>
        public static string TITLE_ADD_SOURCE_DIRECTORY {
            get {
                return ResourceManager.GetString("TITLE_ADD_SOURCE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source file.
        /// </summary>
        public static string TITLE_ADD_SOURCE_FILE {
            get {
                return ResourceManager.GetString("TITLE_ADD_SOURCE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new backup.
        /// </summary>
        public static string TITLE_NEW_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("TITLE_NEW_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename backup.
        /// </summary>
        public static string TITLE_RENAME_BACKUP_COLLECTION {
            get {
                return ResourceManager.GetString("TITLE_RENAME_BACKUP_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add destination directory.
        /// </summary>
        public static string TOOLTIP_ADD_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source files from directory.
        /// </summary>
        public static string TOOLTIP_ADD_SOURCE_DIRECTORY {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD_SOURCE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source file.
        /// </summary>
        public static string TOOLTIP_ADD_SOURCE_FILE {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD_SOURCE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform backup.
        /// </summary>
        public static string TOOLTIP_BACKUP {
            get {
                return ResourceManager.GetString("TOOLTIP_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove destination directory.
        /// </summary>
        public static string TOOLTIP_REMOVE_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("TOOLTIP_REMOVE_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove source file.
        /// </summary>
        public static string TOOLTIP_REMOVE_SOURCE_FILE {
            get {
                return ResourceManager.GetString("TOOLTIP_REMOVE_SOURCE_FILE", resourceCulture);
            }
        }
    }
}
