name: .NET Myna Backup
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backup
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet publish
    - run: zip -r MynaBackup.zip bin/Release/net8.0-windows/publish
    - uses: actions/upload-artifact@v4
      with:
        path: MynaBackup.zip
